package com.example.fcode12;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.fcode12.UserInfoModel;

import com.example.fcode12.UserInfoModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userInfoModelDaoConfig;

    private final UserInfoModelDao userInfoModelDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userInfoModelDaoConfig = daoConfigMap.get(UserInfoModelDao.class).clone();
        userInfoModelDaoConfig.initIdentityScope(type);

        userInfoModelDao = new UserInfoModelDao(userInfoModelDaoConfig, this);

        registerDao(UserInfoModel.class, userInfoModelDao);
    }
    
    public void clear() {
        userInfoModelDaoConfig.getIdentityScope().clear();
    }

    public UserInfoModelDao getUserInfoModelDao() {
        return userInfoModelDao;
    }

}
